#!/bin/sh
### BEGIN INIT INFO
# Provides:          gpioinit
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:      udev
# Default-Start:     S
# Default-Stop:
# Short-Description: Initialises the GPIO exports
# Description:       Initialises the GPIO exports
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start () {
	echo 17 > /sys/class/gpio/export;
	echo 27 > /sys/class/gpio/export;
	echo 22 > /sys/class/gpio/export;
	echo 23 > /sys/class/gpio/export;

	echo out > /sys/class/gpio/gpio23/direction;
	echo 0 > /sys/class/gpio23/value;

	echo out > /sys/class/gpio/gpio17/direction;
	echo 1 > /sys/class/gpio17/value;

	echo out > /sys/class/gpio/gpio27/direction;
        echo 1 > /sys/class/gpio27/value;

	echo out > /sys/class/gpio/gpio22/direction;
        echo 1 > /sys/class/gpio22/value;

	echo out > /sys/class/gpio/gpio23/direction;
        echo 1 > /sys/class/gpio23/value;
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: initgpio.sh [start]" >&2
        exit 3
        ;;
esac
